import type { FileOperation } from "@/core/changes";
import type { DomainCandidate } from "@/core/candidates";
import type { AnalysisResult } from "@/core/analysis";
import type { RepositoryFile } from "@/core/repository";
import type { StagePlan } from "@/core/stages";
import { assertNormalizedPath } from "@/core/paths";
import { matchPathPattern } from "@/server/validation/envelope";

function domainSlug(candidate: DomainCandidate): string {
  return (
    candidate.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || candidate.id
  );
}

function testRoot(files: readonly RepositoryFile[]): string {
  if (files.some((f) => f.path.startsWith("tests/"))) return "tests";
  if (files.some((f) => f.path.startsWith("test/"))) return "test";
  if (files.some((f) => f.path.startsWith("__tests__/"))) return "__tests__";
  return "tests";
}

/**
 * Deterministic Change Set generator for fixtures / offline demos.
 * Used when TOOLBOX_DETERMINISTIC_GENERATION=1 or AI is unavailable in tests.
 */
function filterOpsToEnvelope(ops: FileOperation[], stage: StagePlan): FileOperation[] {
  return ops.filter((op) => {
    const patterns =
      op.type === "create"
        ? stage.pathEnvelope.create
        : op.type === "update"
          ? stage.pathEnvelope.update
          : stage.pathEnvelope.delete;
    return patterns.some((p) => matchPathPattern(p, op.path));
  });
}

export function generateDeterministicOperations(input: {
  stage: StagePlan;
  candidate: DomainCandidate;
  analysis: AnalysisResult;
  files: readonly RepositoryFile[];
}): FileOperation[] {
  const slug = domainSlug(input.candidate);
  const moduleRoot = `src/modules/${slug}`;
  const modelName = input.candidate.primaryModel?.modelName ?? input.candidate.name;
  const collection = input.candidate.primaryModel?.collectionName ?? `${slug.replace(/-/g, "")}s`;

  const raw = generateDeterministicOperationsUnfiltered(
    input,
    slug,
    moduleRoot,
    modelName,
    collection,
  );
  return filterOpsToEnvelope(raw, input.stage);
}

function generateDeterministicOperationsUnfiltered(
  input: {
    stage: StagePlan;
    candidate: DomainCandidate;
    analysis: AnalysisResult;
    files: readonly RepositoryFile[];
  },
  slug: string,
  moduleRoot: string,
  modelName: string,
  collection: string,
): FileOperation[] {
  switch (input.stage.kind) {
    case "behavior_capture": {
      const root = testRoot(input.files);
      const path = assertNormalizedPath(`${root}/${slug}.characterization.test.js`);
      const routes = input.candidate.routes.slice(0, 4);
      const cases = routes
        .map((r, i) => {
          const full = `${r.mountPrefix ?? ""}${r.path}`.replace(/\/+/g, "/") || "/";
          const method = r.method === "use" || r.method === "all" ? "get" : r.method;
          return `
  it("characterizes ${method.toUpperCase()} ${full} (${i})", async () => {
    const res = await request(app).${method}("${full.split(":")[0] || "/"}");
    expect(res.status).toBeDefined();
  });`;
        })
        .join("\n");
      const content = `const request = require("supertest");
const { createApp } = require("../app");

/**
 * Characterization tests for ${input.candidate.name}.
 * Generated by ToolBox — not executed against external repositories.
 */
describe("${input.candidate.name} characterization", () => {
  const app = createApp();
${cases || `  it("placeholder", () => { expect(true).toBe(true); });`}
});
`;
      return [{ type: "create", path, content }];
    }

    case "domain_module": {
      const modelPath = assertNormalizedPath(`${moduleRoot}/${slug}.model.js`);
      const repoPath = assertNormalizedPath(`${moduleRoot}/${slug}.repository.js`);
      const servicePath = assertNormalizedPath(`${moduleRoot}/${slug}.service.js`);
      const controllerPath = assertNormalizedPath(`${moduleRoot}/${slug}.controller.js`);
      const routesPath = assertNormalizedPath(`${moduleRoot}/${slug}.routes.js`);
      const indexPath = assertNormalizedPath(`${moduleRoot}/index.js`);

      const modelContent = `const mongoose = require("mongoose");

const schema = new mongoose.Schema(
  {
    userId: { type: String, required: true },
    total: { type: Number, required: true },
    status: {
      type: String,
      enum: ["pending", "paid", "cancelled"],
      default: "pending",
    },
  },
  { collection: ${JSON.stringify(collection)} },
);

const ${modelName} = mongoose.models.${modelName} || mongoose.model(${JSON.stringify(modelName)}, schema);

module.exports = ${modelName};
`;

      const repoContent = `const ${modelName} = require("./${slug}.model");

async function findAll() {
  return ${modelName}.find({});
}

async function create(data) {
  return ${modelName}.create(data);
}

async function updateOne(filter, update) {
  return ${modelName}.updateOne(filter, update);
}

module.exports = {
  findAll,
  create,
  updateOne,
  model: ${modelName},
};
`;

      const serviceContent = `const repository = require("./${slug}.repository");

const memory = [];
let seq = 1;

function list() {
  return memory.slice();
}

function create(input) {
  const item = {
    id: "${slug.slice(0, 3)}_" + seq++,
    ...input,
    status: input.status || "pending",
  };
  memory.push(item);
  return item;
}

function getById(id) {
  return memory.find(function match(x) {
    return x.id === id;
  });
}

async function listFromDb() {
  return repository.findAll();
}

module.exports = {
  list,
  create,
  getById,
  listFromDb,
  repository,
};
`;

      const controllerContent = `const service = require("./${slug}.service");

async function list(_req, res) {
  const items = service.list();
  res.json({ ${slug.replace(/-/g, "")}s: items, orders: items });
}

async function get(req, res) {
  const found = service.getById(req.params.id);
  if (!found) return res.status(404).json({ error: "not_found" });
  return res.json({ order: found, item: found });
}

async function create(req, res) {
  const body = req.body || {};
  if (!body.userId || typeof body.total !== "number") {
    return res.status(400).json({ error: "invalid" });
  }
  const item = service.create({ userId: String(body.userId), total: body.total });
  return res.status(201).json({ order: item, payment: { status: "quoted" } });
}

async function cancel(req, res) {
  const found = service.getById(req.params.id);
  if (!found) return res.status(404).json({ error: "not_found" });
  found.status = "cancelled";
  return res.json({ order: found });
}

module.exports = {
  list,
  get,
  create,
  cancel,
};
`;

      const routesContent = `const express = require("express");
const controller = require("./${slug}.controller");

const router = express.Router();

router.get("/", controller.list);
router.get("/:id", controller.get);
router.post("/", controller.create);
router.post("/:id/cancel", controller.cancel);

module.exports = router;
module.exports.listOpenOrderIds = function listOpenOrderIds() {
  return [];
};
`;

      const indexContent = `const router = require("./${slug}.routes");
const service = require("./${slug}.service");
const repository = require("./${slug}.repository");
const model = require("./${slug}.model");

function create${input.candidate.name}Module(deps) {
  return {
    router: router,
    service: service,
    repository: repository,
    model: model,
    deps: deps || {},
  };
}

module.exports = {
  router,
  service,
  repository,
  model,
  create${input.candidate.name}Module,
  // read-only facade
  list: service.list,
  getById: service.getById,
};
`;

      const entry = input.files.find((f) => f.path === input.analysis.entryPath);
      const entryContent = entry?.content ?? "";
      const binding = `${slug.replace(/-/g, "_")}Module`;
      let updatedEntry = entryContent;
      // Prefer a named module require so mount prefix resolution can map binding → public index.
      if (/require\(["']\.\/routes\/orders["']\)/.test(updatedEntry)) {
        updatedEntry = updatedEntry
          .replace(
            /const\s+ordersRouter\s*=\s*require\(["']\.\/routes\/orders["']\);?/,
            `const ${binding} = require("./${moduleRoot}");\nconst ordersRouter = ${binding}.router;`,
          )
          .replace(/require\(["']\.\/routes\/orders["']\)/g, `${binding}.router`);
        if (!updatedEntry.includes(`require("./${moduleRoot}")`)) {
          updatedEntry = `const ${binding} = require("./${moduleRoot}");\n` + updatedEntry;
        }
      } else if (!updatedEntry.includes(moduleRoot)) {
        updatedEntry =
          `const ${binding} = require("./${moduleRoot}");\n` +
          entryContent.replace(
            /app\.use\(\s*["']\/orders["']\s*,\s*\w+\s*\)/,
            `app.use("/orders", ${binding}.router)`,
          );
      }

      const ops: FileOperation[] = [
        { type: "create", path: modelPath, content: modelContent },
        { type: "create", path: repoPath, content: repoContent },
        { type: "create", path: servicePath, content: serviceContent },
        { type: "create", path: controllerPath, content: controllerContent },
        { type: "create", path: routesPath, content: routesContent },
        { type: "create", path: indexPath, content: indexContent },
      ];
      if (entry && updatedEntry !== entryContent) {
        ops.push({
          type: "update",
          path: assertNormalizedPath(input.analysis.entryPath),
          content: updatedEntry,
        });
      }
      return ops;
    }

    case "cycle_repair": {
      const indexPath = assertNormalizedPath(`${moduleRoot}/index.js`);
      const existingIndex = input.files.find((f) => f.path === indexPath);
      const indexContent =
        existingIndex?.content ??
        `module.exports = { create${input.candidate.name}Module: function create() { return {}; } };\n`;

      const paymentsPath = assertNormalizedPath("routes/payments.js");
      const ordersLegacy = assertNormalizedPath("routes/orders.js");
      const payments = input.files.find((f) => f.path === paymentsPath);
      const orders = input.files.find((f) => f.path === ordersLegacy);
      const entry = input.files.find((f) => f.path === input.analysis.entryPath);

      const ops: FileOperation[] = [];

      // Break cycle: payments should not require orders statically for listOpenOrderIds
      if (payments && /require\(["']\.\/orders["']\)/.test(payments.content)) {
        const fixed = payments.content.replace(
          /const\s+\w+\s*=\s*require\(["']\.\/orders["']\);?/,
          "/* cycle broken: orders injected via composition root */\nlet ordersApi = { listOpenOrderIds: function () { return []; } };\nfunction setOrdersApi(api) { ordersApi = api; }",
        );
        // also fix usages of previous binding if needed - keep summarize
        const withExport = fixed + `\nmodule.exports.setOrdersApi = setOrdersApi;\n`;
        ops.push({ type: "update", path: paymentsPath, content: withExport });
      }

      if (orders && /require\(["']\.\/payments["']\)/.test(orders.content)) {
        // leave orders requiring payments OR inject - prefer remove static require if module exists
        const fixed = orders.content.replace(
          /const\s+payments\s*=\s*require\(["']\.\/payments["']\);?/,
          "let payments = { summarizeForOrder: function () { return { status: 'quoted' }; } };",
        );
        ops.push({ type: "update", path: ordersLegacy, content: fixed });
      }

      const factoryIndex = indexContent.includes("create")
        ? indexContent
        : indexContent +
          `\nfunction create${input.candidate.name}Module(deps) {\n  return { deps: deps || {}, router: module.exports.router };\n}\nmodule.exports.create${input.candidate.name}Module = create${input.candidate.name}Module;\n`;
      if (existingIndex) {
        ops.push({ type: "update", path: indexPath, content: factoryIndex });
      }

      if (entry) {
        let entryContent = entry.content;
        if (!/setOrdersApi|createOrdersModule|create.*Module/.test(entryContent)) {
          entryContent =
            entryContent +
            `\n// composition-root injection for cycle repair\ntry {\n  const paymentsRouter = require("./routes/payments");\n  const ordersMod = require("./src/modules/${slug}");\n  if (paymentsRouter && typeof paymentsRouter.setOrdersApi === "function" && ordersMod) {\n    paymentsRouter.setOrdersApi(ordersMod);\n  }\n} catch (_e) {}\n`;
          ops.push({
            type: "update",
            path: assertNormalizedPath(input.analysis.entryPath),
            content: entryContent,
          });
        }
      }

      return ops.length > 0
        ? ops
        : [
            {
              type: "update",
              path: assertNormalizedPath(input.analysis.entryPath),
              content:
                (entry?.content ?? "") +
                `\n// cycle repair no-op marker\nmodule.exports.__cycleRepaired = true;\n`,
            },
          ];
    }

    case "integration_cleanup": {
      const ops: FileOperation[] = [];
      const indexPath = assertNormalizedPath(`${moduleRoot}/index.js`);
      const hasModule = input.files.some((f) => f.path === indexPath);
      if (!hasModule) {
        return [];
      }

      // Only rewire files that still require a selected-domain legacy path.
      const legacyNeedles = input.candidate.files.map((f) => f as string);
      for (const file of input.files) {
        if (!file.path.endsWith(".js")) continue;
        if (file.path.startsWith(`${moduleRoot}/`)) continue;
        const touchesLegacy = legacyNeedles.some((legacy) => {
          const base = legacy.replace(/\.js$/, "");
          return (
            file.content.includes(`'${legacy}'`) ||
            file.content.includes(`"${legacy}"`) ||
            file.content.includes(`'./${legacy}'`) ||
            file.content.includes(`"./${legacy}"`) ||
            file.content.includes(`'../${legacy}'`) ||
            file.content.includes(`"../${legacy}"`) ||
            new RegExp(`require\\(['"](?:\\.\\.?/)*${base.replace(/\//g, "\\/")}['"]\\)`).test(
              file.content,
            )
          );
        });
        if (!touchesLegacy) continue;

        let updated = file.content;
        for (const legacy of legacyNeedles) {
          if (legacy.endsWith(".js") && /routes\//.test(legacy)) {
            const rel = legacy.replace(/^routes\//, "");
            updated = updated
              .replace(
                new RegExp(`require\\(["']\\./routes/${rel.replace(/\.js$/, "")}["']\\)`, "g"),
                `require("./${moduleRoot}")`,
              )
              .replace(
                new RegExp(`require\\(["']\\.\\./routes/${rel.replace(/\.js$/, "")}["']\\)`, "g"),
                `require("../${moduleRoot}")`,
              );
          }
          if (legacy.endsWith(".js") && /models\//.test(legacy)) {
            const rel = legacy.replace(/^models\//, "").replace(/\.js$/, "");
            updated = updated
              .replace(
                new RegExp(`require\\(["']\\./models/${rel}["']\\)`, "g"),
                `require("./${moduleRoot}").model`,
              )
              .replace(
                new RegExp(`require\\(["']\\.\\./models/${rel}["']\\)`, "g"),
                `require("../${moduleRoot}").model`,
              );
          }
        }
        if (updated !== file.content) {
          ops.push({
            type: "update",
            path: assertNormalizedPath(file.path),
            content: updated,
          });
        }
      }

      // Delete only selected-domain legacy files with no remaining require references
      // in the post-update snapshot (excluding the file itself and module internals).
      const deleted = new Set<string>();
      const contentAfter = (path: string, original: string): string => {
        const upd = ops.find((o) => o.type === "update" && o.path === path);
        return upd && upd.type === "update" ? upd.content : original;
      };

      for (const legacy of input.candidate.files) {
        if (legacy.startsWith(`${moduleRoot}/`)) continue;
        if (legacy === input.analysis.entryPath) continue;
        const stillReferenced = input.files.some((f) => {
          if (f.path === legacy) return false;
          if (deleted.has(f.path)) return false;
          if (f.path.startsWith(`${moduleRoot}/`)) return false;
          const body = contentAfter(f.path, f.content);
          const base = legacy.split("/").pop()?.replace(/\.js$/, "") ?? legacy;
          return (
            body.includes(legacy) || new RegExp(`require\\(['"][^'"]*${base}['"]\\)`).test(body)
          );
        });
        if (!stillReferenced) {
          ops.push({ type: "delete", path: assertNormalizedPath(legacy) });
          deleted.add(legacy);
        }
      }

      if (ops.length === 0) {
        const index = input.files.find((f) => f.path === indexPath);
        ops.push({
          type: "update",
          path: indexPath,
          content:
            (index?.content ?? "module.exports = {};\n") + "\n// integration cleanup: no-op\n",
        });
      }
      return ops;
    }

    default:
      return [];
  }
}
